### PR TITLE
Creating skeleton

### PR DESCRIPTION
**Pull request by calveym**
Added functions.py. Added requirements.txt.

functions.py will contain all logic processing to convert raw JSON data
into usable information.

### CODE REVIEW

**Comment by calveym** [comment]
@whiterd

**Comment by randdane** [comment]
I have noticed that the main functionality of a lot of modules seem to have the same name as the app itself. Any comments on this?

**Comment by randdane** [comment]
```
~/realprice
    |-- run.py
    |-- config.py
    |__ /env             # Virtual Environment
    |__ /app             # Our Application Module
         |-- __init__.py
         |-- /module_one
             |-- __init__.py
             |-- controllers.py
             |-- models.py                
         |__ /templates
             |__ /module_one
                 |-- hello.html
         |__ /static
         |__ ..
         |__ .
    |__ ..
    |__ .
```

I also found the structure above from [here.](https://www.digitalocean.com/community/tutorials/how-to-structure-large-flask-applications) It recommends this for large Flask apps. Should we have something similar?

**Comment by calveym** [comment]
@whiterd it seems like a pretty good idea to copy or at least use something like that for inspiration. I haven't delved into flask much yet, but I'm trying to get on top of it now. We will have to use the correct structure for the whole thing to work. Our project is a bit different from the example, because it is mostly backend processing like the wrapper and logic, as opposed to numerous dynamic pages. There will probably only be a couple separate pages for display, although that's up to the UI team.

**Comment by calveym** [comment]
Good idea on the naming, I might have a look at that. Most of the skeleton I am creating here is for logic and processing, to get the raw JSON data we receive from the wrapper into a format acceptable for use by the UI crew. We will still have to do all of the actual backend/ requests stuff separately.

**Pull request merged**
